// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        int64
	MovieID   int64
	ProfileID int64
	Content   string
	CreatedAt time.Time
}

type Genre struct {
	ID   int32
	Name string
}

type Movie struct {
	ID              int64
	Title           string
	OriginalTitle   *string
	Description     *string
	Director        *string
	ReleaseDate     pgtype.Date
	DurationMinutes *int32
	PosterUrl       *string
	AverageRating   pgtype.Numeric
	ViewsCount      int64
	CreatedAt       time.Time
}

type MovieGenre struct {
	MovieID int64
	GenreID int32
}

type Profile struct {
	ID         int64
	AuthUserID int64
	Username   string
	AvatarUrl  *string
	Bio        *string
	CreatedAt  time.Time
}

type Rating struct {
	ID        int64
	MovieID   int64
	ProfileID int64
	Score     int16
	CreatedAt time.Time
}

type UserFavorite struct {
	UserID    int64
	MovieID   int64
	CreatedAt time.Time
}
