// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        int64
	MovieID   pgtype.Int8
	ProfileID pgtype.Int8
	Content   string
	CreatedAt pgtype.Timestamptz
}

type Genre struct {
	ID   int32
	Name string
}

type Movie struct {
	ID              int64
	Title           string
	OriginalTitle   pgtype.Text
	Description     pgtype.Text
	Director        pgtype.Text
	ReleaseDate     pgtype.Date
	DurationMinutes pgtype.Int4
	PosterUrl       pgtype.Text
	AverageRating   pgtype.Numeric
	ViewsCount      pgtype.Int8
	CreatedAt       pgtype.Timestamptz
}

type MovieGenre struct {
	MovieID int64
	GenreID int32
}

type Profile struct {
	ID         int64
	AuthUserID int64
	Username   string
	AvatarUrl  pgtype.Text
	Bio        pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type Rating struct {
	ID        int64
	MovieID   pgtype.Int8
	ProfileID pgtype.Int8
	Score     int16
	CreatedAt pgtype.Timestamptz
}
