// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO user_favorites (user_id, movie_id)
VALUES ($1, $2)
ON CONFLICT (user_id, movie_id) DO NOTHING
`

type AddFavoriteParams struct {
	UserID  int64
	MovieID int64
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.MovieID)
	return err
}

const addGenreToMovie = `-- name: AddGenreToMovie :exec
INSERT INTO movie_genres (movie_id, genre_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddGenreToMovieParams struct {
	MovieID int64
	GenreID int32
}

func (q *Queries) AddGenreToMovie(ctx context.Context, arg AddGenreToMovieParams) error {
	_, err := q.db.Exec(ctx, addGenreToMovie, arg.MovieID, arg.GenreID)
	return err
}

const createComment = `-- name: CreateComment :one

INSERT INTO comments (movie_id, user_id, text)
VALUES ($1, $2, $3)
RETURNING id, movie_id, user_id, text, created_at, updated_at
`

type CreateCommentParams struct {
	MovieID int64
	UserID  int64
	Text    string
}

// ============================================================================
// COMMENTS
// ============================================================================
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.MovieID, arg.UserID, arg.Text)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.UserID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies (
    title,
    original_title,
    description,
    director,
    release_date,
    duration_minutes,
    poster_url
) VALUES (
             $1,
             $2,
             $3,
             $4,
             $5::date,
             $6,
             $7
         )
RETURNING id
`

type CreateMovieParams struct {
	Title           string
	OriginalTitle   *string
	Description     *string
	Director        *string
	ReleaseDate     pgtype.Date
	DurationMinutes *int32
	PosterUrl       *string
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMovie,
		arg.Title,
		arg.OriginalTitle,
		arg.Description,
		arg.Director,
		arg.ReleaseDate,
		arg.DurationMinutes,
		arg.PosterUrl,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createProfile = `-- name: CreateProfile :one

INSERT INTO profiles (auth_user_id, username, avatar_url, bio)
VALUES (
           $1,
           $2,
           $3,
           $4
       )
RETURNING id, auth_user_id, username, avatar_url, bio, created_at
`

type CreateProfileParams struct {
	AuthUserID int64
	Username   string
	AvatarUrl  *string
	Bio        *string
}

// ============================================================================
// PROFILES
// ============================================================================
func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.AuthUserID,
		arg.Username,
		arg.AvatarUrl,
		arg.Bio,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE id = $1 AND user_id = $2
`

type DeleteCommentParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.Exec(ctx, deleteComment, arg.ID, arg.UserID)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, movie_id, user_id, text, created_at, updated_at
FROM comments
WHERE id = $1
`

func (q *Queries) GetCommentByID(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.UserID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMovieByID = `-- name: GetMovieByID :one

SELECT
    m.id,
    m.title,
    m.original_title,
    m.description,
    m.director,
    m.release_date,
    m.duration_minutes,
    m.poster_url,
    m.average_rating::float8 AS average_rating,
    m.views_count,
    m.created_at,
    COALESCE(ARRAY_AGG(g.name) FILTER (WHERE g.name IS NOT NULL), '{}')::TEXT[] AS genres
FROM movies m
         LEFT JOIN movie_genres mg ON m.id = mg.movie_id
         LEFT JOIN genres g ON mg.genre_id = g.id
WHERE m.id = $1
GROUP BY m.id
`

type GetMovieByIDRow struct {
	ID              int64
	Title           string
	OriginalTitle   *string
	Description     *string
	Director        *string
	ReleaseDate     pgtype.Date
	DurationMinutes *int32
	PosterUrl       *string
	AverageRating   float64
	ViewsCount      int64
	CreatedAt       time.Time
	Genres          []string
}

// ============================================================================
// MOVIES & GENRES
// ============================================================================
func (q *Queries) GetMovieByID(ctx context.Context, id int64) (GetMovieByIDRow, error) {
	row := q.db.QueryRow(ctx, getMovieByID, id)
	var i GetMovieByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.OriginalTitle,
		&i.Description,
		&i.Director,
		&i.ReleaseDate,
		&i.DurationMinutes,
		&i.PosterUrl,
		&i.AverageRating,
		&i.ViewsCount,
		&i.CreatedAt,
		&i.Genres,
	)
	return i, err
}

const getProfileByAuthID = `-- name: GetProfileByAuthID :one
SELECT id, auth_user_id, username, avatar_url, bio, created_at
FROM profiles
WHERE auth_user_id = $1
LIMIT 1
`

func (q *Queries) GetProfileByAuthID(ctx context.Context, authUserID int64) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByAuthID, authUserID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
	)
	return i, err
}

const incrementMovieViews = `-- name: IncrementMovieViews :exec
UPDATE movies
SET views_count = views_count + 1
WHERE id = $1
`

func (q *Queries) IncrementMovieViews(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementMovieViews, id)
	return err
}

const incrementMovieViewsBy = `-- name: IncrementMovieViewsBy :exec
UPDATE movies
SET views_count = views_count + $2
WHERE id = $1
`

type IncrementMovieViewsByParams struct {
	ID         int64
	ViewsCount int64
}

func (q *Queries) IncrementMovieViewsBy(ctx context.Context, arg IncrementMovieViewsByParams) error {
	_, err := q.db.Exec(ctx, incrementMovieViewsBy, arg.ID, arg.ViewsCount)
	return err
}

const isFavorite = `-- name: IsFavorite :one
SELECT EXISTS (
    SELECT 1
    FROM user_favorites
    WHERE user_id = $1 AND movie_id = $2
)
`

type IsFavoriteParams struct {
	UserID  int64
	MovieID int64
}

func (q *Queries) IsFavorite(ctx context.Context, arg IsFavoriteParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFavorite, arg.UserID, arg.MovieID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFavorites = `-- name: ListFavorites :many
SELECT
    m.id,
    m.title,
    m.original_title,
    m.description,
    m.release_date,
    m.duration_minutes,
    m.poster_url,
    m.average_rating,
    m.views_count,
    uf.created_at AS added_at
FROM user_favorites uf
         JOIN movies m ON m.id = uf.movie_id
WHERE uf.user_id = $1
ORDER BY uf.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFavoritesParams struct {
	UserID int64
	Limit  int32
	Offset int32
}

type ListFavoritesRow struct {
	ID              int64
	Title           string
	OriginalTitle   *string
	Description     *string
	ReleaseDate     pgtype.Date
	DurationMinutes *int32
	PosterUrl       *string
	AverageRating   pgtype.Numeric
	ViewsCount      int64
	AddedAt         time.Time
}

func (q *Queries) ListFavorites(ctx context.Context, arg ListFavoritesParams) ([]ListFavoritesRow, error) {
	rows, err := q.db.Query(ctx, listFavorites, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavoritesRow
	for rows.Next() {
		var i ListFavoritesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.OriginalTitle,
			&i.Description,
			&i.ReleaseDate,
			&i.DurationMinutes,
			&i.PosterUrl,
			&i.AverageRating,
			&i.ViewsCount,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovieComments = `-- name: ListMovieComments :many
SELECT id, movie_id, user_id, text, created_at, updated_at
FROM comments
WHERE movie_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListMovieCommentsParams struct {
	MovieID int64
	Limit   int32
	Offset  int32
}

func (q *Queries) ListMovieComments(ctx context.Context, arg ListMovieCommentsParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listMovieComments, arg.MovieID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.UserID,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovies = `-- name: ListMovies :many
SELECT
    m.id,
    m.title,
    m.original_title,
    m.description,
    m.director,
    m.release_date,
    m.duration_minutes,
    m.poster_url,
    m.average_rating::float8 AS average_rating,
    m.views_count,
    m.created_at,
    COALESCE(ARRAY_AGG(g.name) FILTER (WHERE g.name IS NOT NULL), '{}')::TEXT[] AS genres
FROM movies m
         LEFT JOIN movie_genres mg ON m.id = mg.movie_id
         LEFT JOIN genres g ON mg.genre_id = g.id
WHERE ($1::INT IS NULL OR mg.genre_id = $1)
GROUP BY m.id
ORDER BY m.created_at DESC
LIMIT $3 OFFSET $2
`

type ListMoviesParams struct {
	GenreID *int32
	Offset  int32
	Limit   int32
}

type ListMoviesRow struct {
	ID              int64
	Title           string
	OriginalTitle   *string
	Description     *string
	Director        *string
	ReleaseDate     pgtype.Date
	DurationMinutes *int32
	PosterUrl       *string
	AverageRating   float64
	ViewsCount      int64
	CreatedAt       time.Time
	Genres          []string
}

func (q *Queries) ListMovies(ctx context.Context, arg ListMoviesParams) ([]ListMoviesRow, error) {
	rows, err := q.db.Query(ctx, listMovies, arg.GenreID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMoviesRow
	for rows.Next() {
		var i ListMoviesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.OriginalTitle,
			&i.Description,
			&i.Director,
			&i.ReleaseDate,
			&i.DurationMinutes,
			&i.PosterUrl,
			&i.AverageRating,
			&i.ViewsCount,
			&i.CreatedAt,
			&i.Genres,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM user_favorites
WHERE user_id = $1 AND movie_id = $2
`

type RemoveFavoriteParams struct {
	UserID  int64
	MovieID int64
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.MovieID)
	return err
}

const updateMovieRating = `-- name: UpdateMovieRating :exec
UPDATE movies
SET average_rating = (
    SELECT COALESCE(AVG(score), 0.0)
    FROM ratings
    WHERE movie_id = $1
)
WHERE id = $1
`

func (q *Queries) UpdateMovieRating(ctx context.Context, movieID int64) error {
	_, err := q.db.Exec(ctx, updateMovieRating, movieID)
	return err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET
    username = COALESCE($1, username),
    avatar_url = COALESCE($2, avatar_url),
    bio = COALESCE($3, bio)
WHERE auth_user_id = $4
RETURNING id, auth_user_id, username, avatar_url, bio, created_at
`

type UpdateProfileParams struct {
	Username   *string
	AvatarUrl  *string
	Bio        *string
	AuthUserID int64
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.Username,
		arg.AvatarUrl,
		arg.Bio,
		arg.AuthUserID,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.AuthUserID,
		&i.Username,
		&i.AvatarUrl,
		&i.Bio,
		&i.CreatedAt,
	)
	return i, err
}

const upsertRating = `-- name: UpsertRating :exec

INSERT INTO ratings (movie_id, profile_id, score)
VALUES ($1, $2, $3)
ON CONFLICT (movie_id, profile_id)
    DO UPDATE SET score = EXCLUDED.score, created_at = CURRENT_TIMESTAMP
`

type UpsertRatingParams struct {
	MovieID   int64
	ProfileID int64
	Score     int16
}

// ============================================================================
// RATINGS
// ============================================================================
func (q *Queries) UpsertRating(ctx context.Context, arg UpsertRatingParams) error {
	_, err := q.db.Exec(ctx, upsertRating, arg.MovieID, arg.ProfileID, arg.Score)
	return err
}
