env: "local" # local, dev, prod

grpc:
  port: 45045
  timeout: 5s

postgres:
  host: "localhost"
  port: 1291
  user: "postgres"
  password: "postgres"
  dbname: "movie_db"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 5555
  password: ""

kafka:
  brokers:
    - "localhost:9092"
  comments_topic: "movie-comments"

auth_service:
  address: "localhost:44044"
  app_id: 45045
  app_secret: "dd20e5ec-4ec9-4f82-8dac-787482f90670"